spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      # Swagger 3.0 error
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
      path: /h2_db
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  secret_key: n2r5u8x/A%DG-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%CF-J@NcRfrknfkjdoiskd
  token-validity-in-seconds: 86400

file:
  itemimgLocation: C:/shop/item

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

